### PR TITLE
README: Provide Startup Instructions

### PR DESCRIPTION
**Pull request by SmallJoker**
I don't know how else you're supposed to use this well functioning DLL, so here are some instructions for newcomers.
Also works on Linux + Wine.

### CODE REVIEW

**Comment by SmallJoker** [comment]
On mm2x I've seen archives that contain `MM2Hook.exe`, so could it be that only the recent builds lack of an executable?

**Comment by Deebz96** [comment]
There has never been an executable. Where did you see this?

**Comment by Dummiesman** [comment]
You don't need a DLL injector to use this on Linux. Open winecfg and set dinput.dll to use the local DLL instead of the Wine one, and it will work without any further tweaks.

**Comment by SmallJoker** [comment]
> There has never been an executable. Where did you see this?

I checked the [Chicago map](https://www.mm2x.com/modules.php?name=Downloads&op=getit&lid=1388) archive again and noticed that it's called `MM2Hack.exe` and the configuration is different as well. Sorry for the false alert.

> Open winecfg and set dinput.dll to use the local DLL instead of the Wine one, and it will work without any further tweaks.

Thank you. So that's another method to get it running. I'll adjust the PR accordingly.

**Pull request closed without merging**
