### PR TITLE
Updated the README with commonly used arguments.

### PR DESCRIPTION
**Pull request by Diatosta**

### CODE REVIEW

**Comment by Fireboyd78** [comment]
A lot of those are actually in MM2 by default. This may also be better as a wiki page instead of on the readme. It'd also be helpful to format everything into a table-like format, because as it stands it's very difficult to read and just doesn't fit well with everything else. See [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables) for information on how to make tables (using GitHub's flavor of Markdown).

My suggestion for table layout:

| Argument | Parameters | Description |
| ----------- | :------------: | ------------- |
| -nopause | _N/A_| Allows the game to keep running even when unfocused. |
| -heapsize | `size_in_mb` | Sets the heap size, in megabytes. (e.g. `-heapsize 256` for a 256MB heap) |

Up to you on how the table should be laid out, however.

**Comment by Keith94** [comment]
Is there a full list of available command line arguments? Would be useful!

**Comment by Fireboyd78** [comment]
@Keith94 Are you asking for ones included in MM2 by default? Or just MM2Hook ones?

**Comment by Keith94** [comment]
Both, if possible!

**Comment by Fireboyd78** [comment]
@Diatosta Please let me know if you're interested in fixing the formatting, otherwise I'll have to decline this PR.

**Pull request merged**
